# fly.toml file generated for pdns-dnsdist on 2023-01-04T11:50:35+01:00

app = "pdns"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DNSDISTCONF_BACKEND_IP = "fdaa:1:160b:0:1::3" # internal PDNS IPv6 IP
  DNSDIST_ENABLE_RECURSOR = "false" # if enabled set also Recursor IP and Main Domain
  # DNSDISTCONF_RECURSOR_IP = "9.9.9.9" # recursor ip
  # DNSDISTCONF_MAIN_DOMAIN = "dnskrake.top" #only if recursor enabled
  # PDNS_WORKER_IP = "fdaa:1:160b:0:1::4" # curl a list of domains from somewhere

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 53
  protocol = "udp"

  [services.concurrency]
    hard_limit = 100
    soft_limit = 80
    type = "connections"

  [[services.ports]]
    port = "53"

[[services]]
  internal_port = 53
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 100
    soft_limit = 80
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.ports]]
    port = "53"

[[services]]
  http_checks = []
  internal_port = 80
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 80
    soft_limit = 60
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[metrics]
  port = 8083
  path = "/metrics"